import { getUsersById } from '../services/get-user-by-id';

export default async function UsersDetailsHead({
  params,
}: {
  params: { userId: string };
}) {
  const user = await getUsersById(params.userId);
  const title = `${user.first_name} - Usuário do sistema Olá Mundo`;
  return (
    <>
      <title>{title}</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </>
  );
}
