export default function UsersHead() {
  return (
    <>
      <title>Usuários: Sistema Olá Mundo!</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />

      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
